In [299]:
import pandas as pd   
data=pd.read_csv("./amazon_product.csv")

In [300]:
data.head(6)

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
5,5,B0CSB22F9C,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$129.99,$137.65,USD,4.2,578,https://www.amazon.com/dp/B0CSB22F9C,https://m.media-amazon.com/images/I/51rp0nqaPo...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN

In [301]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   64 non-null     int64
 1   asin                         64 non-null     object
 2   product_title                64 non-null     object
 3   product_price                64 non-null     object
 4   product_original_price       27 non-null     object
 5   currency                     64 non-null     object
 6   product_star_rating          54 non-null     float64
 7   product_num_ratings          64 non-null     int64
 8   product_url                  64 non-null     object
 9   product_photo                64 non-null     object
 10  product_num_offers           64 non-null     int64
 11  product_minimum_offer_price  64 non-null     object
 12  is_best_seller               64 non-null     bool
 13  is_amazon_choice             64 non-null     bool
 14  is_prime                     64 non-null     bool
 15  climate_pledge_friendly      64 non-null     bool
 16  sales_volume                 61 non-null     object
 17  delivery                     63 non-null     object
 18  has_variations               64 non-null     bool
 19  product_availability         1 non-null      object
 20  unit_price                   5 non-null      object
 21  unit_count                   5 non-null      float64
dtypes: bool(5), float64(2), int64(3), object(12)
memory usage: 8.9+ KB

In [302]:
data.columns

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='object')

In [303]:
""" Deleting redundant columns.
 Renaming the columns. 
 Dropping duplicates. 
 Remove the NaN values from the dataset Check for transformation"""

' Deleting redundant columns.\n Renaming the columns. \n Dropping duplicates. \n Remove the NaN values from the dataset Check for transformation'

In [304]:
data.columns

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='object')

In [305]:
data.drop(columns=['Unnamed: 0', 'asin','product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price','is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations'],inplace=True)

In [306]:
data.columns

Index(['product_title', 'product_price', 'product_original_price', 'currency',
       'product_star_rating', 'product_num_ratings', 'is_best_seller',
       'product_availability', 'unit_price', 'unit_count'],
      dtype='object')

In [307]:
new_columns=[]
for i in data.columns:
    new_columns.append(i.capitalize())

In [308]:
new_columns

['Product_title',
 'Product_price',
 'Product_original_price',
 'Currency',
 'Product_star_rating',
 'Product_num_ratings',
 'Is_best_seller',
 'Product_availability',
 'Unit_price',
 'Unit_count']

In [309]:
data.columns=new_columns

In [310]:
data.head(6)

,Product_title,Product_price,Product_original_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller,Product_availability,Unit_price,Unit_count
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,False,NaN,NaN,NaN
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,False,Only 7 left in stock - order soon.,NaN,NaN
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,False,NaN,NaN,NaN
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,False,NaN,NaN,NaN
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,False,NaN,NaN,NaN
5,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$129.99,$137.65,USD,4.2,578,False,NaN,NaN,NaN

In [311]:
data.duplicated().sum()

np.int64(0)

In [312]:
# if duplicates then
# drop.duplicates(inplace=True)

In [313]:
data.isna().sum()

Product_title              0
Product_price              0
Product_original_price    37
Currency                   0
Product_star_rating       10
Product_num_ratings        0
Is_best_seller             0
Product_availability      63
Unit_price                59
Unit_count                59
dtype: int64

In [314]:
data=data[["Product_title","Product_price","Currency","Product_num_ratings","Is_best_seller"]]

In [315]:
data.isna().sum()

Product_title          0
Product_price          0
Currency               0
Product_num_ratings    0
Is_best_seller         0
dtype: int64

In [316]:
data.dropna()
data

,Product_title,Product_price,Currency,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,2929,False
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,USD,135,False
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,USD,205,False
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,USD,2248,False
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,USD,423,False
...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,USD,0,False
60,Swan Song,$14.99,USD,14471,True
61,Bluey: Let&#x27;s Play!,$0.00,USD,270,False
62,Xbox Wireless Controller â€“ Sky Cipher Special ...,$69.99,USD,12,True
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,USD,48154,True

In [317]:
data["Is_best_seller"]=data["Is_best_seller"].apply(lambda x: 1 if x==True else 0)
data

,Product_title,Product_price,Currency,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,USD,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,USD,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,USD,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,USD,423,0
...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,USD,0,0
60,Swan Song,$14.99,USD,14471,1
61,Bluey: Let&#x27;s Play!,$0.00,USD,270,0
62,Xbox Wireless Controller â€“ Sky Cipher Special ...,$69.99,USD,12,1
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,USD,48154,1

In [320]:
data["Product_price"]=data["Product_price"].str.replace("$","")
data

,Product_title,Product_price,Currency,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,USD,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,USD,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,49.88,USD,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335.00,USD,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,USD,423,0
...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,34.98,USD,0,0
60,Swan Song,14.99,USD,14471,1
61,Bluey: Let&#x27;s Play!,0.00,USD,270,0
62,Xbox Wireless Controller â€“ Sky Cipher Special ...,69.99,USD,12,1
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,59.99,USD,48154,1

In [321]:
data["Product_price"]=data["Product_price"].astype(float)
data

,Product_title,Product_price,Currency,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,USD,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,USD,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,49.88,USD,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335.00,USD,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,USD,423,0
...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,34.98,USD,0,0
60,Swan Song,14.99,USD,14471,1
61,Bluey: Let&#x27;s Play!,0.00,USD,270,0
62,Xbox Wireless Controller â€“ Sky Cipher Special ...,69.99,USD,12,1
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,59.99,USD,48154,1

In [325]:
data["Product_price"]=data["Product_price"].apply( lambda x: round(x) )
data

,Product_title,Product_price,Currency,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,100,USD,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",150,USD,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,50,USD,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335,USD,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",200,USD,423,0
...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,35,USD,0,0
60,Swan Song,15,USD,14471,1
61,Bluey: Let&#x27;s Play!,0,USD,270,0
62,Xbox Wireless Controller â€“ Sky Cipher Special ...,70,USD,12,1
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,60,USD,48154,1

In [326]:
data.to_excel("Cleaned_DATA.xlsx",index=False)